// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwprrknjphbijkiklzhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cHJya25qcGhiaWpraWtsemhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDg0NTYsImV4cCI6MjA2ODkyNDQ1Nn0.J_pxCQPLEalyMTrFp4iU2u50Q2FVj9dUnVkqUoGvi0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});